### ISSUE TITLE
Redis Scope driver?

### ISSUE THREAD

**Issue by martianatwork** [netsells/laravel-geoscope#1]
The library is great, can we support redis as scopedriver?

**Comment by AdamHutchison** [comment]
Thanks for the feedback @martianatwork. Currently geoscope is limited to the database connections available to your laravel app, by default that's MySQL, Postgres, SQL Server and SQLite (although SQLite requires a custom scope driver) so out of the box Redis is not supported. Redis does have native support for geo distance calculations though so I'll add the inclusion of a redis facade macro to the feature list for the next release. Feel free to drop me a message with details of your use case so I can make sure it supports what you're trying to do.
