### ISSUE TITLE
ST_Distance_Sphere does not exist because of MariaDB

### ISSUE THREAD

**Issue by kurumbus** [netsells/laravel-geoscope#2]
Hey thank you for wonderful package. 

So locally everything works fine, but I have MariaDB on the server and it doesn't have ST_Distance_Sphere function which you use in MySQLScopeDriver.

Error is
```
"SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION zoohelper_ru.ST_Distance_Sphere does not exist (SQL: select *,             ROUND(ST_Distance_Sphere(↵                    point(doctors.longitude, doctors.latitude),↵                    point(30.3302085, 59.8463368)↵                ) * 0.001, 2) as distance, 'kilometers' as distance_units from `doctors` where exists (select * from `species` inner join `doctor_species` on `species`.`id` = `doctor_species`.`species_id` where `doctors`.`id` = `doctor_species`.`doctor_id` and `species`.`id` = 1) and `latitude` is not null and `longitude` is not null order by             ST_Distance_Sphere(↵                    point(doctors.longitude, doctors.latitude),↵                    point(30.3302085, 59.8463368)↵                ) * 0.001 asc limit 50)"
```

And they can't fix that for 3 years already: https://jira.mariadb.org/browse/MDEV-13467

Any workaround you'd suppose I could do? I think I could fork and create a MariaDB driver and make a PR (with some guidance)

**Comment by nagi1** [comment]
I had the same problem I referred to this solution here
https://stackoverflow.com/a/56669074/6686248

**Comment by AdamHutchison** [comment]
Hi @kurumbus many thanks for the feedback. I'll take a look over the next few days and see if I can add support for mariaDB. If it's possible then I'll add a release with it in. In the meantime, the package does support the creation and registration of custom scope drivers and you can force a specific driver to be used in the config.

**Comment by kurumbus** [comment]
@AdamHutchison we did a fork as a matter of fact and it's working on our site. https://github.com/nomadicsoft/laravel-geoscope

I just don't make a PR because we didn't write tests (ain't anybody got time for that). But if you're OK with it, I will make a PR

**Comment by AdamHutchison** [comment]
Yes please @kurumbus. I'll add the tests and then create a new release.

**Comment by kurumbus** [comment]
@AdamHutchison srry for the delay https://github.com/netsells/laravel-geoscope/pull/4

**Comment by AdamHutchison** [comment]
Many thanks for contributing @kurumbus
