### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION harvesine.ST_Distance_Sphere does not exist 

### ISSUE THREAD

**Issue by cloudeweb** [netsells/laravel-geoscope#6]
Hi, I'm using your package in localhost with 10.1.35-MariaDB version.

I've added this 'scope-driver' => 'mysql', but I get this follow error: 
SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION harvesine.ST_Distance_Sphere does not exist 

Can you help me?
thanks!

**Comment by AdamHutchison** [comment]
Hi @cloudeweb. Because mariadb uses the same DB connection driver as mysql in laravel you need to explicitly set the scope driver to `mariadb` in your `geoscope,php` config file. e.g.

```php
    'defaults' => [
        'lat-column' => 'latitude',
        'long-column' => 'longitude',
        'units' => 'miles',
        'scope-driver' => 'mariadb',
    ],
```

Give me a shout if you need any more help.

**Comment by cloudeweb** [comment]
Works fine! but with only 3 results I get a lot of queries: ​5 statements were executed, 4 of which were duplicated, 1 unique.

With classic harvesine code I get 1 query only.

This is my code:

$jobs = Job::addDistanceFromField($lat, $lng, 'custom_field_name')
                      ->orderByDistanceFrom($lat, $lng, 'asc')
                      ->get();

thanks!
